# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=4.0.9+26.3-BETA
maven_group=net.borisshoes
archives_base_name=arcananovum
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.160.5+26.3
borislib_version=3.4.5+26.3
sgui_version=2.2.0+26.3
polymer_version=0.18.2+26.3
factorytools_version=0.12.1+26.3
translation_version=3.2.0+26.3
fabric_permissions_api_version=0.7.0
pal_version=1.16.0
voicechat_version=2.6.23+26.3