# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=4.0.8+26.2
maven_group=net.borisshoes
archives_base_name=arcananovum
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.152.1+26.2
borislib_maven_version=diTY48i1
borislib_mod_version=3.4.1+26.2-ALPHA
sgui_version=2.1.0+26.2
polymer_version=0.17.0+26.2-rc-2
factorytools_version=0.11.0+26.2
translation_version=3.1.0+26.2
fabric_permissions_api_version=0.7.0
pal_version=1.16.0
voicechat_version=2.6.20+26.2